= Readme
maokelong <maoeklong@qq.com>
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:stylesheet:
:icons: font

== 配置环境

首先最好确保当前操作系统的版本是 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-releases/16.04/[Unbuntu 16.04]。

=== 下载内核

本项目基于 Linux v4.19.49 开发。

[source,bash]
----
wget https://mirrors.tuna.tsinghua.edu.cn/kernel/v4.x/linux-4.19.49.tar.gz
tar -xvzf linux-4.19.49.tar.gz
----

=== 修改内核

在开发的过程中，出于两种需求：1）使得 WellPM 能够利用内核中的部分函数；2）使得内核能够处理 WellPM 引入的新型页错误，我们对内核做了一定修改。

[source,bash]
----
pwd # 当前目录为 wpmfs-bench
patch -Np0 < tools/patch/dax.c.patch
patch -Np0 < tools/patch/fault.c.patch 
patch -Np0 < tools/patch/vmalloc.c.patch 
----

=== 安装内核

. 安装依赖项
+
[source,bash]
----
sudo apt install build-essential libncurses5-dev bison flex \
    openssl libssl-dev libelf-dev -y
----
. 安装内核
[source,bash]
----
pwd # 当前目录为 wpmfs-bench
cd linux-4.19.49
make menuconfig # 该步直接 Save 即可
make -j$(cat /proc/cpuinfo | grep "processor" | wc -l)
sudo make modules_install
sudo make install
sudo update-grub
----

=== 模拟持久内存

我们需要预留一定持久内存用于挂载 WellPM。在较新的内核下可直接执行如下操作，而无需额外修改内核配置文件。

* 预留 PM 地址空间；
. 预留多少？
+
查询可得可用地址空间 `0x0000000100000000-0x0000000c3fffffff`，也就是 4G~49G。这里预留 16GB。
+
[source,bash]
----
dmesg | grep BIOS
----
. 怎么预留？
+
编辑 GRUB，使启动内核时使用指定内核命令行参数「memmap=16G!4G」从 4G 开始的位置预留 16GB。
+
[source,shell]
----
# 编辑 GRUB 配置，修改成「GRUB_CMDLINE_LINUX="memmap=16G!4G"」
sudo gedit /etc/default/grub
# 更新 GRUB 引导程序，可能不是 grub2 而是 grub
sudo grub-mkconfig -o /boot/grub/grub.cfg
# 重启，使用最新的引导程序进入系统
sudo reboot
# 查看 user-defined physical RAM map
dmesg | grep user
----

== 安装 WellPM-bench

=== 安装 Filebench

将 https://github.com/filebench/filebench[Filebench] 安装到 `macro_bench/filebench` 目录。

=== 安装 Whisper

将 https://github.com/swapnilh/whisper[Whisper] 安装到 `macro_bench/whisper` 目录。

WARNING: 该步无需执行。多数测试场景下无需运行 Whisper，因此这里暂时屏蔽了相关代码。

== 运行 WellPM-bench

[source,shell]
----
bash run.sh
----

执行的时候终端上会打印 benchmark 的 OPS，且执行完毕后 output 目录会生成两种类型的图标：一张反映所有块写入次数的图，一张反映某百分位页预期寿命的图。

== 配置 WellPM

WellPM 目前提供了一些配置项。目前配置仅能通过直接修改 `wpmfs/scripts/config.sh` 中的变量进行配置。

对配置项的解释如下：

* CONFIG_PATH_PMEM_DEV
+
模拟的持久内存
* CONFIG_FS_INIT_HARD
+
硬启动方式挂载
* CONFIG_FS_DBGMASK
+
开启调试项
* CONFIG_FS_TIMING
+
统计关键功能的执行时间
* CONFIG_FS_ENABLE_TRACKING
+
开启写追踪
* CONFIG_FS_ENABLE_VMAP
+
将部分内存映射到 vmalloc space
* CONFIG_FS_ALLOCATOR
+
选择分配器
* CONFIG_FS_WL_SWITCH
+
选择损耗均衡功能（0 关闭）
* CONFIG_FS_INT_THRES
+
页迁移阈值（以 2 为底的幂）
* CONFIG_FS_CELL_ENDUR
+
单元寿命（以 2 为底的幂）
